# linux-fslc (community, mainline-based) bbappend — DT510 mainline experiment.
#
# EXPERIMENT: branch experiment/dt510-mainline-kernel.
# Target: linux-fslc 6.12 LTS (KBRANCH 6.12.x+fslc, LINUX_VERSION 6.12.13,
# github.com/Freescale/linux-fslc). Selected for imx8mm-jaguar-dt510 by
# PREFERRED_PROVIDER_virtual/kernel in conf/machine/imx8mm-jaguar-dt510.conf.
#
# Full rationale + patch-queue triage: docs/DT510-MAINLINE-KERNEL-MIGRATION.md
#
# Status: DT + peripheral stacks wired. The board DTS is reused unchanged (mainline
# build placement handled in do_configure); the charger/audio driver stacks are
# forward-ported from the NXP 6.6 queue onto linux-fslc 6.12 (SRCREV-matched) and
# wired below. First-build verification is via the vixdt CI branch.

FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"
# Shared board DTS + SoC pad-word headers live under lmp-device-tree.
FILESEXTRAPATHS:prepend:imx8mm-jaguar-dt510 := "${THISDIR}/../../recipes-bsp/device-tree/lmp-device-tree:"

# Mirror the vendor recipe's buildpaths QA hardening.
DEBUG_PREFIX_MAP:append = " -fdebug-prefix-map=${TMPDIR}=/usr/src/debug/tmpdir"
DEBUG_PREFIX_MAP:append = " -fdebug-prefix-map=${WORKDIR}=/usr/src/debug/${PN}/${PV}"

# --- Device tree ---
# DT rebase finding (see migration doc): the canonical imx8mm-jaguar-dt510.dts is
# already mainline-compatible for compile — every referenced &label resolves in
# mainline imx8mm.dtsi/imx8mm-evk.dtsi/imx8mm-evkb.dts, and the /delete-node/ ops
# that target NXP-only nodes (sound-ak4458/5558/4497, regulator-audio-board, the
# ak*@1x codecs) are by-NAME deletes → no-ops on mainline (dtc does not error).
# So we reuse the canonical DTS unchanged and only adjust BUILD PLACEMENT for the
# mainline arm64 layout (DTBs live in freescale/Makefile, not the top dts/Makefile).
SRC_URI:append:imx8mm-jaguar-dt510 = " \
    file://imx8mm-jaguar-dt510.dts \
    file://imx8mm-sw_pad_ctl.h \
    file://imx8mm-sw_pad_ctl-fields.h \
"

# --- Peripheral driver stacks, forward-ported from the NXP 6.6 queue onto 6.12 ---
# Generated by rebasing the vendor patch queue onto linux-fslc SRCREV e92f5b7050c7
# (= linux-fslc_6.12.bb SRCREV, 6.12.34) in _kernel-work; see migration doc worklist.
# Applied in numeric order (they build on each other). 6.6-compat shims and
# already-upstream imports were dropped during the forward-port. kernel-yocto
# (via linux-imx.inc) applies the .patch files and merges the loose .cfg fragments.
SRC_URI:append:imx8mm-jaguar-dt510 = " \
    file://imx8mm-jaguar-dt510/patches/0001-mfd-bq257xx-Add-BQ25703A-MFD-core-linux-fslc-6.6-con.patch \
    file://imx8mm-jaguar-dt510/patches/0002-power-supply-bq257xx-Add-support-for-BQ257XX-charger.patch \
    file://imx8mm-jaguar-dt510/patches/0003-regulator-bq257xx-Add-bq257xx-boost-regulator-driver.patch \
    file://imx8mm-jaguar-dt510/patches/0004-dt-bindings-mfd-ti-bq25703a-Import-binding-from-main.patch \
    file://imx8mm-jaguar-dt510/patches/0005-dt-bindings-mfd-ti-bq25703a-Expand-to-include-BQ2579.patch \
    file://imx8mm-jaguar-dt510/patches/0006-regulator-bq257xx-Remove-reference-to-the-parent-MFD.patch \
    file://imx8mm-jaguar-dt510/patches/0007-regulator-bq257xx-Drop-the-regulator_dev-from-the-dr.patch \
    file://imx8mm-jaguar-dt510/patches/0008-regulator-bq257xx-Make-OTG-enable-GPIO-really-option.patch \
    file://imx8mm-jaguar-dt510/patches/0009-power-supply-bq257xx-Fix-VSYSMIN-clamping-logic.patch \
    file://imx8mm-jaguar-dt510/patches/0010-power-supply-bq257xx-Make-the-default-current-limit-.patch \
    file://imx8mm-jaguar-dt510/patches/0011-power-supply-bq257xx-Consistently-use-indirect-get-s.patch \
    file://imx8mm-jaguar-dt510/patches/0012-power-supply-bq257xx-Add-fields-for-charging-and-ove.patch \
    file://imx8mm-jaguar-dt510/patches/0013-mfd-bq257xx-Add-BQ25792-support.patch \
    file://imx8mm-jaguar-dt510/patches/0014-regulator-bq257xx-Add-support-for-BQ25792.patch \
    file://imx8mm-jaguar-dt510/patches/0015-power-supply-bq257xx-Add-support-for-BQ25792.patch \
    file://imx8mm-jaguar-dt510/patches/0016-ASoC-pcm6240-PRE_POWER_UP-on-capture-stream-startup-.patch \
    file://imx8mm-jaguar-dt510/patches/0017-ASoC-pcm6240-enable-ASI-TX-I2S32-PASI0-on-capture-DT.patch \
    file://imx8mm-jaguar-dt510/patches/0018-dt-bindings-mfd-Add-bindings-for-TI-TAC5x1x-MFD-core.patch \
    file://imx8mm-jaguar-dt510/patches/0019-dt-bindings-pinctrl-Add-bindings-for-TI-TAC5x1x-pinc.patch \
    file://imx8mm-jaguar-dt510/patches/0020-dt-bindings-sound-Add-bindings-for-TI-TAC5x1x-codec.patch \
    file://imx8mm-jaguar-dt510/patches/0021-mfd-tac5x1x-Add-TI-TAC5x1x-MFD-core-driver.patch \
    file://imx8mm-jaguar-dt510/patches/0022-pinctrl-pinctrl-tac5x1x-Add-TI-TAC5x1x-pinctrl-drive.patch \
    file://imx8mm-jaguar-dt510/patches/0023-ASoC-tac5x1x-Add-TI-TAC5x1x-codec-driver.patch \
    file://imx8mm-jaguar-dt510/patches/0024-ASoC-tac5x1x-wire-into-codecs-Makefile-6.12-y-style.patch \
    file://imx8mm-jaguar-dt510/patches/0025-mfd-tac5x1x-DT510-TAC5301-analog-DT-defaults.patch \
    file://imx8mm-jaguar-dt510/patches/0026-ASoC-tas6424-rename-mixer-controls-for-passenger-tan.patch \
    file://imx8mm-jaguar-dt510/patches/0027-ASoC-fsl_sai-fix-SAI5-sync-rx-capture-clocks-DT510-T.patch \
    file://imx8mm-jaguar-dt510/bq25792-charger.cfg \
    file://imx8mm-jaguar-dt510/bq257xx-mfd-kconfig.cfg \
    file://imx8mm-jaguar-dt510/cp2108-usb-serial.cfg \
    file://imx8mm-jaguar-dt510/ksz9896-ethernet-switch.cfg \
    file://imx8mm-jaguar-dt510/ksz9896-mii-phy.cfg \
    file://imx8mm-jaguar-dt510/mcp251xfd-can.cfg \
    file://imx8mm-jaguar-dt510/pcm6240-audio-codec.cfg \
    file://imx8mm-jaguar-dt510/pmic-pca9450.cfg \
    file://imx8mm-jaguar-dt510/rdc-driver.cfg \
    file://imx8mm-jaguar-dt510/tac5x1x.cfg \
    file://imx8mm-jaguar-dt510/tas2562-audio-codec.cfg \
    file://imx8mm-jaguar-dt510/tas6424-audio-codec.cfg \
    file://imx8mm-jaguar-dt510/usb-audio-gadget.cfg \
    file://imx8mm-jaguar-dt510/video-disable.cfg \
    file://imx8mm-jaguar-dt510/wifi-power-management.cfg \
"

# Mainline arm64 DTB wiring: place the board DTS in freescale/ (so its
# #include "freescale/imx8mm-evkb.dts" is rewritten to the sibling path) and add
# its dtb rule to freescale/Makefile (top-level dts/Makefile is subdir-y only).
do_configure:append:imx8mm-jaguar-dt510(){
 dst=${S}/arch/arm64/boot/dts/freescale
 if [ -f ${WORKDIR}/imx8mm-jaguar-dt510.dts ]; then
     install -m0644 ${WORKDIR}/imx8mm-jaguar-dt510.dts ${dst}/imx8mm-jaguar-dt510.dts
     # DTS now sits inside freescale/, so drop the freescale/ include prefix.
     sed -i 's|freescale/imx8mm-evkb.dts|imx8mm-evkb.dts|' ${dst}/imx8mm-jaguar-dt510.dts
     [ -f ${WORKDIR}/imx8mm-sw_pad_ctl.h ] && install -m0644 ${WORKDIR}/imx8mm-sw_pad_ctl.h ${dst}/
     [ -f ${WORKDIR}/imx8mm-sw_pad_ctl-fields.h ] && install -m0644 ${WORKDIR}/imx8mm-sw_pad_ctl-fields.h ${dst}/
     grep -q 'imx8mm-jaguar-dt510.dtb' ${dst}/Makefile || \
         echo 'dtb-$(CONFIG_ARCH_MXC) += imx8mm-jaguar-dt510.dtb' >> ${dst}/Makefile
 else
     bbwarn "imx8mm-jaguar-dt510.dts not found in ${WORKDIR}"
 fi
}
