/* SPDX-License-Identifier: (GPL-2.0 OR MIT) */
#ifndef __IMX8MM_SW_PAD_CTL_H
#define __IMX8MM_SW_PAD_CTL_H

#include "imx8mm-sw_pad_ctl-fields.h"

#define IMX8MM_PAD_PULLUP_BUS \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_PUE_UP)
#define IMX8MM_PAD_UART_DEFAULT                 IMX8MM_PAD_PULLUP_BUS
#define IMX8MM_PAD_SPI_HOST_DEFAULT             IMX8MM_PAD_PULLUP_BUS
#define IMX8MM_PAD_GPIO_STRAP_PULLUP            IMX8MM_PAD_PULLUP_BUS
#define IMX8MM_PAD_GPIO_DIO_WEAK \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X2)
#define IMX8MM_PAD_GPIO_STD \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X6 | IMX8MM_SW_PAD_CTL_PUE_DOWN)
#define IMX8MM_PAD_GPIO_DIO_INPUT_NOPULL \
       (IMX8MM_SW_PAD_CTL_PE_DIS | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X1)
#define IMX8MM_PAD_GPIO_DEFAULT                 IMX8MM_PAD_GPIO_STD
#define IMX8MM_PAD_I2S_BUS                      IMX8MM_PAD_GPIO_STD
#define IMX8MM_PAD_I2S_SYNC                     IMX8MM_PAD_GPIO_STD
#define IMX8MM_PAD_I2S_FRAME_SYNC_EXT           0x1916
#define IMX8MM_PAD_USDHC_CLK \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X1)
#define IMX8MM_PAD_USDHC_BUS \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_PUE_UP | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X1)
#define IMX8MM_PAD_USDHC_CLK_100MHZ \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X2)
#define IMX8MM_PAD_USDHC_BUS_100MHZ \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_PUE_UP | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X2)
#define IMX8MM_PAD_USDHC_CLK_200MHZ \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X6)
#define IMX8MM_PAD_USDHC_BUS_200MHZ \
       (IMX8MM_SW_PAD_CTL_PE_EN | IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_PUE_UP | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X6)
#define IMX8MM_PAD_ENET_MDIO                    0x03
#define IMX8MM_PAD_ENET_RGMII_TX                0x1f
#define IMX8MM_PAD_ENET_RGMII_RX                0x91
#define IMX8MM_PAD_SAI_DEFAULT \
       (IMX8MM_SW_PAD_CTL_HYS_SCHMITT | IMX8MM_SW_PAD_CTL_PUE_UP | IMX8MM_SW_PAD_CTL_FSEL_FAST | IMX8MM_SW_PAD_CTL_DSE_X6)

#endif /* __IMX8MM_SW_PAD_CTL_H */
