[package]
name = "xm125-radar-monitor"
version = "1.1.0"
edition = "2021"
authors = ["Alex J Lennon <ajlennon@dynamicdevices.co.uk>"]
description = "Production CLI tool for Acconeer XM125 radar modules"
homepage = "https://github.com/DynamicDevices/xm125-radar-monitor"
repository = "https://github.com/DynamicDevices/xm125-radar-monitor"
license = "GPL-3.0-or-later"
readme = "README.md"

[[bin]]
name = "xm125-radar-monitor"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
anyhow = "1.0"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
